# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Open Vocabulary Part Segmentation Challenge
short_description: This Open Vocabulary Part Segmentation (OV-PARTS) challenge is hosted by the Visual Perception via Learning in an Open World (VPLOW) Workshop.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.png
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: This challenge encourages participants to uncover the potential of existing foundation models for addressing OV-PARTS.
evaluation_script: evaluation_script/
remote_evaluation: False
is_docker_based: False
start_date: 2024-04-05 00:00:00
end_date: 2024-06-10 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["h-IoU", "mIoU", "mIoU-base", "mIoU-unbase"],
        "default_order_by": "h-IoU",
        "metadata": {

        }
      }
  - id: 2
    schema:
      {
        "labels": ["h-IoU", "mIoU", "mIoU-base", "mIoU-unbase"],
        "default_order_by": "mIoU",
        "metadata": {
          
        }
      }

challenge_phases:
  - id: 1
    name: Track 1 Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2024-04-05 00:00:00
    end_date: 2024-06-10 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev1
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 60
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
    is_restricted_to_select_one_submission: True
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"
  - id: 2
    name: Track 2 Dev Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2024-04-05 00:00:00
    end_date: 2024-06-10 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev2
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 60
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
    is_restricted_to_select_one_submission: True
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"

dataset_splits:
  - id: 1
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 2
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
